# Generated by Django 3.0.6 on 2020-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=256)),
                ('esal', models.IntegerField()),
                ('eaddr', models.CharField(max_length=256)),
            ],
        ),
    ]
